const neighborhoods = [
  { name: "Downtown Dallas"},
  { name: "City Center District"},
  { name: "Convention Center District"},
  { name: "Farmers Market District"},
  { name: "Government District"},
  { name: "Main Street District"},
  { name: "Reunion District"},
  { name: "West End Historic District"},

  { name: "East Dallas"},
  { name: "Alger Park/Ash Creek"},
  { name: "Belmont"},
  { name: "Buckner Terrace"},
  { name: "Caruth Terrace"},
  { name: "Casa Linda Estates"},
  { name: "Casa View"},
  { name: "Claremont Addition"},
  { name: "Edgemont Park"},
  { name: "Forest Hills"},
  { name: "Gaston Park"},
  { name: "Greenland Hills"},
  { name: "Hollywood Heights"},
  { name: "Junius Heights"},
  { name: "Lake Park Estates"},
  { name: "Lakewood"},
  { name: "Lakewood Heights"},
  { name: "Lakewood Trails"},
  { name: "Little Forest Hills"},
  { name: "Lochwood"},
  { name: "Lower Greenville"},
  { name: "Merriman Park/University Manor"},
  { name: "North Stonewall Terrace"},
  { name: "Old Lake Highlands"},
  { name: "Ridgewood Park"},
  { name: "Santa Monica"},
  { name: "Stonewall Terrace"},
  { name: "University Meadows"},
  { name: "Vickery Place"},
  { name: "Wilshire Heights"},

  {name: "Old East Dallas"},
  { name: "Baylor/Meadows"},
  { name: "Belmont Park"},
  { name: "Bryan Place"},
  { name: "Deep Ellum"},
  { name: "Munger Place Historic District"},
  { name: "Peak's Suburban Addition"},
  { name: "Swiss Avenue"},

  {name: "Lake Highlands"},
  { name: "Abrams Place"},
  { name: "Alexander's Village"},
  { name: "Boundbrook Oaks Estates"},
  { name: "Chimney Hill"},
  { name: "Copperfield Community"},
  { name: "Country Forest"},
  { name: "Forest highlands"},
  { name: "Glen Oaks"},
  { name: "Hamilton Park"},
  { name: "Highlands West"},
  { name: "Highland Meadows"},
  { name: "High Oaks Addition"},
  { name: "Jackson Meadow"},
  { name: "L Streets"},
  { name: "Lake Highlands Estates"},
  { name: "Lake Highlands North"},
  { name: "Lake Highlands Square"},
  { name: "Lake Ridge Estates"},
  { name: "Merriman Park Estates"},
  { name: "Merriman Park North"},
  { name: "Moss Farm"},
  { name: "Moss Meadows"},
  { name: "Northwood Heights"},
  { name: "Oak Highlands"},
  { name: "Oak Tree Village"},
  { name: "Pebble Creek"},
  { name: "Richland Park Estates"},
  { name: "Rolling Trails"},
  { name: "Royal Highlands"},
  { name: "Royal Highlands Village"},
  { name: "Stultz Road"},
  { name: "Town Creek"},
  { name: "Royal Lane Village"},
  { name: "Walnut Creek Estates"},
  { name: "Whispering Hills"},
  { name: "White Rock Valley"},
  { name: "Woodbridge"},
  { name: "Woodlands on the Creek"},
  { name: "University Terrace"},
  { name: "Urban Reserve"},

  {name: "North Dallas"},
  { name: "Bent Tree"},
  { name: "Bluffview"},
  { name: "Devonshire"},
  { name: "Greenway Parks"},
  { name: "North Park"},
  { name: "Preston Hollow"},
  { name: "Shannon Estates"},
  { name: "Vickery Meadows"},

  {name: "Far North Dallas"},
  { name: "Bent Tree"},
  { name: "Preston Highlands"},
  { name: "Timberglen"},
  { name: "Far North Dallas"},
  { name: "Melshire Estates"},
  { name: "Northwood Hills"},
  { name: "Platinum Corridor"},
  { name: "Preston Center"},

  { name:"Northwest Dallas" },
  { name: "Koreatown"},
  { name: "Love Field"},
  { name: "Stemmons Corridor"},
  { name: "Arlington Park"},
  { name: "Design District"},

  {name: "Oak Cliff"},
  { name: "Arcadia Park"},
  { name: "Beckley Club Estates"},
  { name: "Bishop Arts District"},
  { name: "Elmwood"},
  { name: "Stevens Park Estates"},
  { name: "Stevens Park Village"},
  { name: "Western Park"},
  { name: "Winnetka Heights"},
  { name: "Wynnewood"},

  { name: "Kessler"},
  { name: "East Kessler Park"},
  { name: "Kessler Highlands"},
  { name: "Kessler Park Estates"},
  { name: "Kessler Plaza"},
  { name: "Kessler Square"},
  { name: "West Kessler"},
  { name: "Kidd Springs"},
  { name: "Kings Highway Conservation District"},
  { name: "Lake Cliff"},
  { name: "L.O. Daniel"},

  { name: "Redbird"},
  { name: "Elderwoods/Elderoaks"},
  { name: "Glenn Oaks"},
  { name: "Wynnewood Hills"},

  { name: "Oak Lawn"},
  { name: "Cityplace"},
  { name: "Uptown"},
  { name: "International Center"},
  { name: "LoMac"},
  { name: "Knox Park"},
  { name: "Perry Heights"},
  { name: "State Thomas"},
  { name: "Turtle Creek"},
  { name: "Oak Lawn"},
  { name: "Victory Park"},
  { name: "West Village"},

  {name: "Southeast Dallas"},
  { name: "Arnold's Station"},
  { name: "Buckner Park"},
  { name: "Cedar Run"},
  { name: "El Barrio (Little Mexico)"},
  { name: "Elam"},
  { name: "Fireside"},
  { name: "Kleberg"},
  { name: "Lake June"},
  { name: "Parkdale"},
  { name: "Pemberton Hill"},
  { name: "Piedmont"},
  { name: "Pleasant Grove"},
  { name: "Pleasant Hills"},
  { name: "Pleasant Mound"},
  { name: "Riverway Estates/Bruton Terrace"},
  { name: "Rylie"},
  { name: "Seagoville/Dallas"},
  { name: "Scyene"},
  { name: "Spruce Square"},
  { name: "Urbandale"},
  { name: "Woodland Springs"},

  {name: "South Dallas"},
  { name: "Bonton"},
  { name: "Cedars"},
  { name: "Dixon Circle"},
  { name: "Exposition Park"},
  { name: "Fair Park"},
  { name: "Highland Hills"},
  { name: "Wheatley Place"},

  {name: "West Dallas"},
  { name: "Eagle Ford"},
  { name: "Greenleaf Village"},
  { name: "La Bajada"},
  { name: "La L'aceate"},
  { name: "La Loma"},
  { name: "Lake West"},
  { name: "Ledbetter Gardens"},
  { name: "Los Altos"},
  { name: "Muncie"},
  { name: "Western Heights"},
  { name: "Westmoreland Heights"}
]

export default neighborhoods;
